TEMS/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TEMS_BLL;
using TEMS_BOL;

namespace TEMS.Controllers
{
    public class MapController : Controller
    {        
        ExpendetureBLL expendBLL = new ExpendetureBLL();
        // GET: Map
        [HttpGet]
        public ActionResult CostCenterProjectList()
        {
            if (Session["USERNAME"] != null)
            {
                CostCenterProjectBOL costproject = new CostCenterProjectBOL();
                List<SelectListItem> CostCenterList = new List<SelectListItem>();
                List<SelectListItem> ProjectList = new List<SelectListItem>();

                CostCenterList = expendBLL.ListCostCenter();
                ProjectList = expendBLL.ListProject();

                costproject.CostCenterList = CostCenterList;
                costproject.ProjectList = ProjectList;

                return View(costproject);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }
        }

        [HttpPost]
        public ActionResult CostCenterProjectList(CostCenterProjectBOL costproject)
        {
            if (Session["USERNAME"] != null)
            {
                CostCenterProjectBLL costprojectbll = new CostCenterProjectBLL();
                List<SelectListItem> CostCenterList = new List<SelectListItem>();
                List<SelectListItem> ProjectList = new List<SelectListItem>();

                CostCenterList = expendBLL.ListCostCenter();
                ProjectList = expendBLL.ListProject();

                costproject.CostCenterList = CostCenterList;
                costproject.ProjectList = ProjectList;
                costproject.CostCenterProjectListData = costprojectbll.CostProjectData(costproject);
                return View(costproject);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }
        }

        [HttpGet]
        public ActionResult AddCostCenterProjectMap()
        {
            if (Session["USERNAME"] != null)
            {
                CostCenterProjectBOL costproject = new CostCenterProjectBOL();
                List<SelectListItem> CostCenterList = new List<SelectListItem>();
                List<SelectListItem> ProjectList = new List<SelectListItem>();

                CostCenterList = expendBLL.ListCostCenter();
                ProjectList = expendBLL.ListProject();

                costproject.CostCenterList = CostCenterList;
                costproject.ProjectList = ProjectList;

                return View(costproject);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCostCenterProjectMap(CostCenterProjectBOL costproject)
        {
            if (Session["USERNAME"] != null)
            {
                CostCenterProjectBLL costprojectbll = new CostCenterProjectBLL();
                List<SelectListItem> CostCenterList = new List<SelectListItem>();
                List<SelectListItem> ProjectList = new List<SelectListItem>();
                CostCenterList = expendBLL.ListCostCenter();
                ProjectList = expendBLL.ListProject();

                string USERID = Session["USERID"].ToString();

                bool CheckAddCostCenterProjectMap = costprojectbll.AddCostCenterProjectMap(costproject, USERID);
                if (CheckAddCostCenterProjectMap == true)
                {
                    TempData["Message"] = "Cost Center Project Map Details Added Successfully !";
                    return RedirectToAction("AddCostCenterProjectMap");
                }
                else
                {
                    TempData["Message"] = "Fail To Add Cost Center Project Map Details !";
                }

                costproject.CostCenterList = CostCenterList;
                costproject.ProjectList = ProjectList;
                return View(costproject);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }
        }

        [HttpGet]
        public ActionResult EditCostCenterProject(string CostProjectMapId)
        {
            if (Session["USERNAME"] != null)
            {
                CostCenterProjectBLL costprojectbll = new CostCenterProjectBLL();
                CostCenterProjectBOL costproject = new CostCenterProjectBOL();
                List<SelectListItem> CostCenterList = new List<SelectListItem>();
                List<SelectListItem> ProjectList = new List<SelectListItem>();
                if (CostProjectMapId != null && CostProjectMapId != "")
                {
                    CostCenterList = expendBLL.ListCostCenter();
                    ProjectList = expendBLL.ListProject();

                    costproject = costprojectbll.EditCostCenterProject(CostProjectMapId);
                }
                else
                {
                    TempData["Message"] = "Invalid Map ID!";
                    return RedirectToAction("CostCenterProjectList");
                }
                costproject.CostCenterList = CostCenterList;
                costproject.ProjectList = ProjectList;
                return View(costproject);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCostCenterProject(CostCenterProjectBOL costproject)
        {
            if (Session["USERNAME"] != null)
            {
                List<SelectListItem> CostCenterList = new List<SelectListItem>();
                List<SelectListItem> ProjectList = new List<SelectListItem>();

                if (ModelState.IsValid)
                {
                    CostCenterProjectBLL costprojectbll = new CostCenterProjectBLL();
                    

                    string USERID = Session["USERID"].ToString();
                    bool EditCostCenterProjectdata = costprojectbll.EditCostCenterProjectData(costproject, USERID);
                    if (EditCostCenterProjectdata == true)
                    {
                        TempData["Message"] = "Map Details Updated Successfully !";
                        return RedirectToAction("AgencyList");
                    }
                    else
                    {
                        TempData["Message"] = "Fail To Update Map Details !";
                        return RedirectToAction("EditCostCenterProject");
                    }
                    
                }
                else
                {
                    TempData["Message"] = "Please Enter Valid Data!";
                }
                costproject.CostCenterList = CostCenterList;
                costproject.ProjectList = ProjectList;
                return View(costproject);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }
        }
    }
}

TEMS/Views/Map/AddCostCenterProjectMap.cshtml
@model TEMS_BOL.CostCenterProjectBOL
@{
    ViewBag.Title = "AddCostCenterProjectMap";
    Layout = "~/Views/Shared/layout.cshtml";

    List<SelectListItem> StatusList = new List<SelectListItem>();
    StatusList.Add(new SelectListItem { Text = "Active", Value = "True" });
    StatusList.Add(new SelectListItem { Text = "InActive", Value = "False" });
}


<link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
<script src="~/plugins/moment/moment.min.js"></script>

<!-- Input Masking -->
<script src="~/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>
<script src="~/plugins/daterangepicker/daterangepicker.js"></script>

<!-- Select2 -->
<script src="~/plugins/select2/js/select2.full.min.js"></script>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/dist/js/ExpendPageValidation.js"></script>

<style>
    fieldset {
        display: block;
        margin-inline-start: 2px;
        margin-inline-end: 2px;
        padding-block-start: 0.35em;
        padding-inline-start: 0.75em;
        padding-inline-end: 0.75em;
        padding-block-end: 0.625em;
        min-inline-size: min-content;
        border-width: 2px;
        border-style: groove;
        border-color: threedface;
        border-image: initial;
        width: 100%;
    }

    legend {
        display: block;
        padding-left: 2px;
        padding-right: 2px;
        border: none;
        width: auto;
    }
</style>

@*--------------- Start 1st Section ---------------*@
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cost Center Project Map List</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Cost Center Project Map</a></li>
                    <li class="breadcrumb-item active">List</li>
                </ol>
            </div>
        </div>
    </div>
</section>
@*--------------- End 1st Section ---------------*@

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <p class="text-center text-danger" id="ErrMsg">@Html.Raw(TempData["Message"])</p>
                </div>
                <div class="card-body">                    
                    <div class="row">
                        <div class="col-12">
                            @using (Html.BeginForm("AddCostCenterProjectMap", "Map", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <fieldset>
                                    <legend>Information:</legend>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label class="control-label astrisk">Cost Center</label>
                                                @Html.DropDownListFor(model => model.CostCenterId, Model.CostCenterList, "--- Select Cost Center --- ", new { @class = "form-control select2" })
                                                @Html.ValidationMessageFor(model => model.CostCenterId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label class="control-label astrisk">Project</label>
                                                @Html.DropDownListFor(model => model.ProjectId, Model.ProjectList, "--- Select project --- ", new { @class = "form-control select2" })
                                                @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label class="control-label astrisk">Status</label>
                                                @Html.DropDownListFor(model => model.Status, StatusList, new { @class = "form-control select2" })
                                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    @*--------------- Modal For Save ---------------*@
                                    <div class="modal" id="submitbutton" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title"></h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body text-center">
                                                    Do You Want To Save???
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                                                    <button class="btn btn-success">Submit</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            }
                            @*--------------- Buttons ---------------*@
                            <div class="row">
                                <div class="col-md-12 text-right">
                                    <div class="form-group top30">
                                        <a class="btn btn-info" href="javascript:history.go(-1)">Back to List</a>
                                        <button type="button" class="btn btn-danger" onclick="fxResetFieldValue()">Reset</button>
                                        <button class="btn btn-success" data-toggle="modal" data-target="#submitbutton">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                 </div>
             </div>
        </div>
    </div>
</section>

<script>
    $(document).ready(function () {
        $('.select2').select2();
    });

    function fxResetFieldValue() {
        location.assign("./CityList");
    }
</script>   

TEMS/Views/Map/CostCenterProjectList.cshtml
@model TEMS_BOL.CostCenterProjectBOL
@{
    ViewBag.Title = "Cost Center Project List";
    Layout = "~/Views/Shared/layout.cshtml";

    List<SelectListItem> StatusList = new List<SelectListItem>();
    StatusList.Add(new SelectListItem { Text = "Active", Value = "True" });
    StatusList.Add(new SelectListItem { Text = "InActive", Value = "False" });
}


<link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
<script src="~/plugins/moment/moment.min.js"></script>

<!-- Input Masking -->
<script src="~/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>
<script src="~/plugins/daterangepicker/daterangepicker.js"></script>

<!-- Select2 -->
<script src="~/plugins/select2/js/select2.full.min.js"></script>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/dist/js/ExpendPageValidation.js"></script>

<style>
    fieldset {
        display: block;
        margin-inline-start: 2px;
        margin-inline-end: 2px;
        padding-block-start: 0.35em;
        padding-inline-start: 0.75em;
        padding-inline-end: 0.75em;
        padding-block-end: 0.625em;
        min-inline-size: min-content;
        border-width: 2px;
        border-style: groove;
        border-color: threedface;
        border-image: initial;
        width: 100%;
    }

    legend {
        display: block;
        padding-left: 2px;
        padding-right: 2px;
        border: none;
        width: auto;
    }
</style>

@*--------------- Start 1st Section ---------------*@
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cost Center Project Map List</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Cost Center Project Map</a></li>
                    <li class="breadcrumb-item active">List</li>
                </ol>
            </div>
        </div>
    </div>
</section>
@*--------------- End 1st Section ---------------*@

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <p class="text-center text-danger" id="ErrMsg">@Html.Raw(TempData["Message"])</p>
                </div>
                <div class="card-body">
                    <div class="row" style="margin: 20px;">
                        <div class="col-12 text-right">
                            <a href="~/Map/AddCostCenterProjectMap" class="btn btn-success"><span> Add Cost Center Project Map</span></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <fieldset>
                                <legend>Search Filter:</legend>
                                @using (Html.BeginForm("CostCenterProjectList", "Map", FormMethod.Post))
                                {
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label class="control-label">Cost Center</label>
                                                @Html.DropDownListFor(model => model.CostCenterId, Model.CostCenterList, "--- All --- ", new { @class = "form-control select2" })
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label class="control-label">Project</label>
                                                @Html.DropDownListFor(model => model.ProjectId, Model.ProjectList, "--- All --- ", new { @class = "form-control select2" })
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label>Status</label>
                                                @Html.DropDownListFor(model => model.Status, StatusList, "--- All ---", new { @class = "form-control select2" })
                                            </div>
                                        </div>

                                        <div class="col-md-12 text-right top30">
                                            <div class="form-group">
                                                <button type="button" class="btn btn-danger" onclick="fxResetFieldValue()">Reset</button>
                                                <button type="submit" class="btn btn-success">Search</button>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </fieldset>
                        </div>
                    </div>

                    <div class="row hidden">
                        <div class="col-12">
                            <fieldset>
                                <legend>Cost Center Project Map Details List:</legend>
                                <table class="table table-bordered table-hover" id="Citytable">
                                    <thead>
                                        <tr>
                                            <th class="custom-th text-center">Sl No.</th>
                                            <th class="custom-th text-center">Cost Center Name</th>
                                            <th class="custom-th text-center">Project Name</th>
                                            <th class="custom-th text-center">Status</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @if (Model.CostCenterProjectListData != null)
                                        {
                                            if (Model.CostCenterProjectListData.Count > 0)
                                            {
                                                int row = 1;
                                                foreach (var item in Model.CostCenterProjectListData)
                                                {
                                                    <tr>
                                                        <td class="custom-th text-center"> 
                                                            <a href="~/Map/EditCostCenterProject?CostProjectMapId=@item.MapId">@(row) </a>
                                                        </td>
                                                        <td class="custom-th text-center">@(item.CostCenterId == null ? "" : item.CostCenterId)</td>
                                                        <td class="custom-th text-center">@(item.ProjectId == null ? "" : item.ProjectId)</td>                                                                                                               
                                                        <td class="custom-th text-center">@(item.Status == null ? "" : item.Status)</td>
                                                    </tr>
                                                    row = row + 1;
                                                }
                                            }
                                            else
                                            {

                                            }
                                        }
                                        else
                                        {

                                        }
                                    </tbody>
                                </table>
                            </fieldset>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $(document).ready(function () {
        $('.select2').select2();
        $('#Citytable').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": true,
            "responsive": true

        });
    });

    $("#RefStateId").change(function () {
        $.get("./GetDistrictList", { STATE_ID: $("#RefStateId").val() }, function (data) {
            $("#RefDistrictId").empty();
            $("#RefDistrictId").append("<option value=''>--- All ---</option>")
            $.each(data, function (index, row) {
                $("#RefDistrictId").append("<option value='" + row.DISTRICT_ID + "'>" + row.DISTRICT_NAME + "</option>")
            });
        });
    });

    function fxResetFieldValue() {
        location.assign("./CityList");
    }
</script>