TEMS/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TEMS_BLL;
using TEMS_BOL;

namespace TEMS.Controllers
{
    public class LoginController : Controller
    {        
        public ActionResult login()
        {
            loginBOL emp = new loginBOL();
            return View(emp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult login(loginBOL emp)
        {
            loginBLL loginbl = new loginBLL();
            var user = loginbl.checkuser(emp);
            if(user == null)
            {
                TempData["Message"] = "Wrong Username or Password";
                return View("login", user);
            }
            else
            {
                Session["USERID"] = user.USER_ID;
                Session["USERNAME"] = user.FULL_NAME;
                Session["ROLLID"] = user.REF_ROLE_ID;
                return RedirectToAction("Dashboard");
            }            
        }

        public ActionResult Logout()
        {
            //int USERID = (int)Session["USERID"];
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("login");
        }

        public ActionResult Dashboard()
        {
            return View();
        }
    }
}

TEMS/Views/Login/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/layout.cshtml";
}

TEMS/Views/Login/login.cshtml
@model TEMS_BOL.loginBOL
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <meta http-equiv='cache-control' content='no-cache'>
    <meta http-equiv='expires' content='0'>
    <meta http-equiv='pragma' content='no-cache'>
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Login</title>
    <link href="/Content/images/favicon.png" rel="icon">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-165383603-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-165383603-2');
    </script>
    
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/fonts/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet" />
    @*<link href="~/Content/Style.css" rel="stylesheet" />*@
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <style>
        html, body {
            min-height: 100%;
        }

        body {
            background: url('./Content/images/bg-login.jpg') no-repeat 0 0 !important;
            background-size: cover !important;
            font-family: 'Lato', sans-serif;
            line-height: 1.42857143;
            color: #333;
            font-size: 14px;
            background-position: center center;
            padding: 50px 0px 20px;
        }

        label {
            font-weight: 500;
            color: #666;
            display: inline-block;
            margin-bottom: 8px;
            margin-bottom: .5rem;
        }

        .login-inner .form-control {
            border-radius: 0;
            height: 40px;
        }

        .loginlogo {
            text-align: center;
            padding: 5% 0 1px;
        }
        .loginborder {
            width: 400px;
            padding: 17px;
            margin: 0 auto;
            background: rgba(255,255,255,0.2);
            border-radius: 8px;
            margin-top: 20px;
        }
        .login-inner {
            background: #fff;
            padding: 26px;            
        }
        .loginheading {
            text-align: center;
            padding: 0 0 20px 0;
            font-size: 18px;
            font-weight: 800;
            text-transform: uppercase;
        }

        .container-login100-form-btn {
            width: 100%;
            display: -webkit-box;
            display: -webkit-flex;
            display: -moz-box;
            display: -ms-flexbox;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            background-color: #fff;
            /*background: #9152f8;*/
        }
        .login-form-btn {
            font-weight: bold;
            font-size: 18px;
            /*color: #555555;*/
            color: white;
            line-height: 1.2;
            display: -webkit-box;
            display: -webkit-flex;
            display: -moz-box;
            display: -ms-flexbox;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 0 20px;
            min-width: 120px;
            height: 50px;
            border-radius: 25px;
            background: #9152f8;
            background: -webkit-linear-gradient(bottom, #7579ff, #b224ef);
            background: -o-linear-gradient(bottom, #7579ff, #b224ef);
            background: -moz-linear-gradient(bottom, #7579ff, #b224ef);
            background: linear-gradient(bottom, #7579ff, #b224ef);
            position: relative;
            /*z-index: 1;*/
            -webkit-transition: all 0.4s;
            -o-transition: all 0.4s;
            -moz-transition: all 0.4s;
            transition: all 0.4s;
            /*background-color: #fff;*/
        }

        .login100-form-btn::before {
            content: "";
            position: absolute;
            z-index: -1;
            width: 100%;
            height: 100%;
            border-radius: 25px;
            background-color: #fff;
            top: 0;
            left: 0;
            opacity: 1;
            -webkit-transition: all 0.4s;
            -o-transition: all 0.4s;
            -moz-transition: all 0.4s;
            transition: all 0.4s;
        }
        /*.login100-form-btn:hover {
            color: #fff;
        }

            .login100-form-btn:hover:before {
                opacity: 0;
            }*/

        button {
            outline: none !important;
            border: none;
            background: transparent;
        }
        @@media screen and (max-width: 400px) {
            .loginborder {
                width: 300px;
            }
        }        

    </style>

</head>
<body>
    @using (Html.BeginForm("login", "Login", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="container">

            <div class="loginlogo" style="font-size:25px">Tour Expenditure Management System</div>
            <div class="loginborder">
                <div class="login-inner">
                    <div class="loginheading">
                        Login to your account
                    </div>
                    <br />
                    <div class="form-group">
                        <label>User Name</label>
                        @Html.EditorFor(model => model.USER_NAME, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email ID" } })
                        @Html.ValidationMessageFor(model => model.USER_NAME, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label>Password</label>
                        @Html.EditorFor(model => model.PASSWORD, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password" } })
                        @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                    </div>

                    @*<button type="button" class="reset" onclick="fxResetFieldValue()">Reset</button>*@
                    <div class="container-login100-form-btn">
                        <button type="submit" class="login-form-btn" id="btnsubmit">Log In</button>
                    </div>
                        <div class="clearfix"></div>
                        <center>
                            <div class="form-group">
                                <span class="text-danger" id="ErrMsg" style="font-size:15px">@Html.Raw(TempData["Message"])</span>
                            </div>
                        </center>

                    </div>
                </div>
        </div>
    }
</body>
</html>

<!--Client Side Validation-->

<script src="~/MDB/js/jquery.min.js"></script>
<script src="~/MDB/js/bootstrap.min.js"></script>
<script src="~/MDB/js/popper.min.js"></script>
<script src="~/MDB/js/mdb.min.js"></script>

<script>
    $(document).ready(function () {
        $('#btnsubmit').click(function () {

            if ($("#USER_NAME").val() == "") {
                alert("Enter the User Name");
                return false;
            }

            if ($("#PASSWORD").val() == "") {
                alert("Enter the Password");
                return false;
            }
        })
    })
</script>