TEMS/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TEMS_BLL;
using TEMS_BOL;
using TEMS_DAL;

namespace TEMS.Controllers
{
    public class MasterController : Controller
    {
        AddNewUserBLL UserBLL = new AddNewUserBLL();
        ExpendetureBLL expendBLL = new ExpendetureBLL();

        public ActionResult UserList()
        {
            if (Session["USERNAME"] != null)
            {
                SearchNewUserBOL search = new SearchNewUserBOL();
                List<SelectListItem> ListRole = new List<SelectListItem>();

                ListRole = UserBLL.RoleList();

                search.ListRole = ListRole;
                return View(search);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }


        }

        [HttpPost]
        public ActionResult UserList(SearchNewUserBOL search)
        {
            SearchNewUserBLL SearchBLL = new SearchNewUserBLL();
            if (Session["USERNAME"].ToString() != null)
            {
                List<SelectListItem> ListRole = new List<SelectListItem>();

                ListRole = UserBLL.RoleList();

                search.UserListReportData = SearchBLL.GetUserList(search);

                search.ListRole = ListRole;
                return View(search);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }

        }



        public ActionResult AddUser()
        {
            if (Session["USERNAME"].ToString() != null)
            {
                AddNewUserBOL User = new AddNewUserBOL();
                List<SelectListItem> ListRole = new List<SelectListItem>();
                List<SelectListItem> ListGrade = new List<SelectListItem>();

                ListRole = UserBLL.RoleList();
                ListGrade = UserBLL.GradeList();

                User.ListRole = ListRole;
                User.ListGrade = ListGrade;
                return View(User);
            }

            else
            {
                return RedirectToAction("login", "Login");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddUser(AddNewUserBOL User)
        {
            if (Session["USERNAME"] != null)
            {
                List<SelectListItem> ListRole = new List<SelectListItem>();
                List<SelectListItem> ListGrade = new List<SelectListItem>();
                if (ModelState.IsValid)
                {
                    string USERNAME = Session["USERNAME"].ToString();
                    int DuplicateUserEmail = UserBLL.CheckDuplicateUserEmail(User);
                    if (DuplicateUserEmail == 0)
                    {
                        bool SaveUser = UserBLL.SaveUserDetails(User, USERNAME);

                        if (SaveUser == true)
                        {
                            TempData["Message"] = "User Details Added Successfully !";

                            return RedirectToAction("AddUser");
                        }
                        else
                        {
                            TempData["Message"] = "Fail To Save User Details !";
                        }
                    }
                    else
                    {
                        TempData["Message"] = "Email ID Already Exists!";
                    }
                }
                ListRole = UserBLL.RoleList();
                ListGrade = UserBLL.GradeList();

                User.ListRole = ListRole;
                User.ListGrade = ListGrade;
                return View(User);
            }

            else
            {
                return RedirectToAction("login", "Login");
            }

        }

        [HttpGet]
        public ActionResult Edit(string UID)
        {
            if (Session["USERNAME"] != null)
            {
                AddNewUserBOL User = new AddNewUserBOL();
                List<SelectListItem> ListRole = new List<SelectListItem>();
                List<SelectListItem> ListGrade = new List<SelectListItem>();
                if (UID != null && UID != "")
                {
                    User = UserBLL.EditUser(UID);
                    ListRole = UserBLL.RoleList();
                    ListGrade = UserBLL.GradeList();

                    User.ListRole = ListRole;
                    User.ListGrade = ListGrade;
                }
                else
                {
                    TempData["Message"] = "Invalid User ID!";
                    return RedirectToAction("UserList");
                }
                return View(User);
            }

            else
            {
                return RedirectToAction("login", "Login");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AddNewUserBOL User)
        {
            if (Session["USERNAME"] != null)
            {
                List<SelectListItem> ListRole = new List<SelectListItem>();
                List<SelectListItem> ListGrade = new List<SelectListItem>();

                if (ModelState.IsValid)
                {
                    string USERNAME = Session["USERNAME"].ToString();
                    //if (User.Password == null)
                    //{
                        int DuplicateUserEmail = UserBLL.CheckDuplicateUserEditEmail(User);
                        if (DuplicateUserEmail == 0)
                        {
                            bool EditUser = UserBLL.EditUserDetails(User, USERNAME);

                            if (EditUser == true)
                            {
                                TempData["Message"] = "User Details Updated Successfully !";

                                return RedirectToAction("UserList");
                            }
                            else
                            {
                                TempData["Message"] = "Fail To Save User Details !";
                            }
                        }
                        else
                        {
                            TempData["Message"] = "Email ID Already Exists!";
                        }

                    ListRole = UserBLL.RoleList();
                    ListGrade = UserBLL.GradeList();

                }
                else
                {
                    TempData["Message"] = "Please Enter Valid Data !";
                }
                User.ListRole = ListRole;
                User.ListGrade = ListGrade;
                return View(User);

            }
            else
            {
                return RedirectToAction("login", "Login");
            }
        }                

        [HttpGet]
        public ActionResult AgencyList()
        {
            if (Session["USERNAME"] != null)
            {
                AddAgencyBOL search = new AddAgencyBOL();
                List<SelectListItem> AgencyNameList = new List<SelectListItem>();

                AgencyNameList = expendBLL.ListAgency();
                search.AgencyNameList = AgencyNameList;
                return View(search);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }


        }

        [HttpPost]        
        public ActionResult AgencyList(AddAgencyBOL search)
        {
            AgencyBLL Agncybll = new AgencyBLL();
            if (Session["USERNAME"] != null)
            {                
                List<SelectListItem> AgencyNameList = new List<SelectListItem>();

                AgencyNameList = expendBLL.ListAgency();

                search.AgencyNameList = AgencyNameList;
                search.AgencyListReportData = Agncybll.GetagencyList(search);
                return View(search);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }


        }

        [HttpGet]
        public ActionResult AddAgency()
        {
            if (Session["USERNAME"] != null)
            {
                AddAgencyBOL agency = new AddAgencyBOL();
                return View(agency);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAgency(AddAgencyBOL agency)
        {
            AgencyBLL Agncybll = new AgencyBLL();
            if (Session["USERNAME"] != null)
            {
                if (ModelState.IsValid)
                {
                    string USERID = Session["USERID"].ToString();
                    bool checkagencydata = Agncybll.AddAgencyData(agency,USERID);

                    if (checkagencydata == true)
                    {
                        TempData["Message"] = "Agency Details Added Successfully !";
                        return RedirectToAction("AddAgency");
                    }
                    else
                    {
                        TempData["Message"] = "Fail To Add Agency Details !";
                    }
                }
                else
                {
                    TempData["Message"] = "Please Enter Valid Data !";
                }
                return View(agency);
            }
            else
            {
                return RedirectToAction("login", "Login");
            }

        }

        [HttpGet]
        public ActionResult EditAgency(string AId)
        {
            AgencyBLL Agncybll = new AgencyBLL();
            if (Session["USERNAME"] != null)
            {
                AddAgencyBOL agency = new AddAgencyBOL();
                if (AId != null && AId != "")
                {
                    agency = Agncybll.EditAgency(AId);
                }
                else
                {
                    TempData["Message"] = "Invalid Agency ID!";

TEMS/Views/Master/AddAgency.cshtml
@model TEMS_BOL.AddAgencyBOL
@{
    ViewBag.Title = "Add Agency";
    Layout = "~/Views/Shared/layout.cshtml";

    List<SelectListItem> StatusList = new List<SelectListItem>();
    StatusList.Add(new SelectListItem { Text = "Active", Value = "True" });
    StatusList.Add(new SelectListItem { Text = "InActive", Value = "False" });
}

<link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
<script src="~/plugins/moment/moment.min.js"></script>

<!-- Input Masking -->
<script src="~/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>
<script src="~/plugins/daterangepicker/daterangepicker.js"></script>

<!-- Select2 -->
<script src="~/plugins/select2/js/select2.full.min.js"></script>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/dist/js/ExpendPageValidation.js"></script>

<style>
    fieldset {
        display: block;
        margin-inline-start: 2px;
        margin-inline-end: 2px;
        padding-block-start: 0.35em;
        padding-inline-start: 0.75em;
        padding-inline-end: 0.75em;
        padding-block-end: 0.625em;
        min-inline-size: min-content;
        border-width: 2px;
        border-style: groove;
        border-color: threedface;
        border-image: initial;
        width: 100%;
    }

    legend {
        display: block;
        padding-left: 2px;
        padding-right: 2px;
        border: none;
        width: auto;
    }
</style>

@*--------------- Start 1st Section ---------------*@
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Add Agency</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Agency</a></li>
                    <li class="breadcrumb-item active">Add</li>
                </ol>
            </div>
        </div>
    </div>
</section>
@*--------------- End 1st Section ---------------*@

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <p class="text-center text-danger" id="ErrMsg">@Html.Raw(TempData["Message"])</p>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <fieldset>
                                <legend>Information:</legend>
                                @using (Html.BeginForm("AddAgency", "Master", FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label astrisk">Agency Name</label>
                                                @Html.TextBoxFor(model => model.AgencyName, new { @class = "form-control", placeholder = "Agency Name" })
                                                @Html.ValidationMessageFor(model => model.AgencyName, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label">Agency Addess</label>
                                                @Html.TextBoxFor(model => model.AgencyAddress, new { @class = "form-control", placeholder = "Agency Addess" })
                                                @Html.ValidationMessageFor(model => model.AgencyAddress, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label">Agency Mobile No.</label>
                                                @Html.TextBoxFor(model => model.AgencyMobileNo, new { @class = "form-control", placeholder = "Agency Mobile No." })
                                                @Html.ValidationMessageFor(model => model.AgencyMobileNo, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label">Agency WhatsApp No.</label>
                                                @Html.TextBoxFor(model => model.AgencyWhatsAppNo, new { @class = "form-control", placeholder = "Agency WhatsApp No." })
                                                @Html.ValidationMessageFor(model => model.AgencyWhatsAppNo, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label">Agency Email ID</label>
                                                @Html.TextBoxFor(model => model.AgencyEmail, new { @class = "form-control", placeholder = "Agency Email ID" })
                                                @Html.ValidationMessageFor(model => model.AgencyEmail, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label astrisk">Status</label>
                                                @Html.DropDownListFor(model => model.Status, StatusList, new { @class = "form-control select2" })
                                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    @*--------------- Modal For Save ---------------*@
                                    <div class="modal" id="submitbutton" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title"></h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body text-center">
                                                    Do You Want To Save!????
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                                                    <button class="btn btn-success">Submit</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </fieldset>
                            @*--------------- Buttons ---------------*@
                            <div class="row">
                                <div class="col-md-12 text-right">
                                    <div class="form-group top30">
                                        <a class="btn btn-info" href="javascript:history.go(-1)">Back to List</a>
                                        <button type="button" class="btn btn-danger" onclick="fxResetFieldValue()">Reset</button>
                                        <button class="btn btn-success" data-toggle="modal" data-target="#submitbutton">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $('.select2').select2();
</script>

TEMS/Views/Master/AddCity.cshtml
@model TEMS_BOL.AddCityBOL
@{
    ViewBag.Title = "Add City";
    Layout = "~/Views/Shared/layout.cshtml";

    List<SelectListItem> StatusList = new List<SelectListItem>();
    StatusList.Add(new SelectListItem { Text = "Active", Value = "True" });
    StatusList.Add(new SelectListItem { Text = "InActive", Value = "False" });
}

<link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
<script src="~/plugins/moment/moment.min.js"></script>

<!-- Input Masking -->
<script src="~/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>
<script src="~/plugins/daterangepicker/daterangepicker.js"></script>

<!-- Select2 -->
<script src="~/plugins/select2/js/select2.full.min.js"></script>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/dist/js/ExpendPageValidation.js"></script>

<style>
    fieldset {
        display: block;
        margin-inline-start: 2px;
        margin-inline-end: 2px;
        padding-block-start: 0.35em;
        padding-inline-start: 0.75em;
        padding-inline-end: 0.75em;
        padding-block-end: 0.625em;
        min-inline-size: min-content;
        border-width: 2px;
        border-style: groove;
        border-color: threedface;
        border-image: initial;
        width: 100%;
    }

    legend {
        display: block;
        padding-left: 2px;
        padding-right: 2px;
        border: none;
        width: auto;
    }
</style>

@*--------------- Start 1st Section ---------------*@
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Add City</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">City</a></li>
                    <li class="breadcrumb-item active">Add</li>
                </ol>
            </div>
        </div>
    </div>
</section>
@*--------------- End 1st Section ---------------*@

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <p class="text-center text-danger" id="ErrMsg">@Html.Raw(TempData["Message"])</p>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <fieldset>
                                <legend>Information:</legend>
                                @using (Html.BeginForm("AddCity", "Master", FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label astrisk">State</label>
                                                @Html.DropDownListFor(model => model.RefStateId, Model.StateList, "--- Select State ---", new { @class = "form-control select2" })
                                                @Html.ValidationMessageFor(model => model.RefStateId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label astrisk">District</label>
                                                @Html.DropDownListFor(model => model.RefDistrictId, Model.DistrictList, "--- Select District --- ", new { @class = "form-control select2" })
                                                @Html.ValidationMessageFor(model => model.RefDistrictId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label astrisk">City Name</label>
                                                @Html.TextBoxFor(model => model.CityName, new { @class = "form-control", placeholder = "City Name" })
                                                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label astrisk">Status</label>
                                                @Html.DropDownListFor(model => model.Status, StatusList, new { @class = "form-control select2" })
                                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    @*--------------- Modal For Save ---------------*@
                                    <div class="modal" id="submitbutton" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title"></h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body text-center">
                                                    Do You Want To Save!????
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                                                    <button class="btn btn-success">Submit</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </fieldset>
                            @*--------------- Buttons ---------------*@
                            <div class="row">
                                <div class="col-md-12 text-right">
                                    <div class="form-group top30">
                                        <a class="btn btn-info" href="javascript:history.go(-1)">Back to List</a>
                                        <button type="button" class="btn btn-danger" onclick="fxResetFieldValue()">Reset</button>
                                        <button class="btn btn-success" data-toggle="modal" data-target="#submitbutton">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $('.select2').select2();

    $(document).ready(function () {
        $("#RefStateId").change(function () {
            $.get("./GetDistrictList", { STATE_ID: $("#RefStateId").val() }, function (data) {
                $("#RefDistrictId").empty();                
                $("#RefDistrictId").append("<option value=''>--- Select District ---</option>")
                $.each(data, function (index, row) {
                    $("#RefDistrictId").append("<option value='" + row.DISTRICT_ID + "'>" + row.DISTRICT_NAME + "</option>")
                });
            });
        });
    });
</script>